apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage
  annotations:
    github.com/project-slug: saksheesingh12/Backstage
spec:
  type: other
  lifecycle: unknown
  owner: guests
